version: '3.1'

volumes:
  postgres:

services:

  db:
    image: postgres:13-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    container_name: adminpostgres
    restart: always
    ports:
      - 8080:8080