name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag server:$(date +%s)
    - name: Discord Message failed
      env:
        DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_ID }}
      uses: Ilshidur/action-discord@0.3.2
      if: ${{ failure() }}
      with:
        args: "Evento: ${{ github.event_name }} User: ${{github.actor}} ha fallado la creacion de la imagen de docker"
    - name: Discord Message success
      env:
        DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_ID }}
      uses: Ilshidur/action-discord@0.3.2
      if: ${{ success() }}
      with:
        args: "se ha creado exitosamente la imagen de docker"